name: "Render Github Pages"
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
    
    jobs:
      launch:
        runs-on: ubuntu-latest
        steps:
          - run: |
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/studsovet-imct/studsovet-imct.github.io/dispatches \
                -d '{"event_type":"new_post_release"}'